### ISSUE TITLE
Requisitos

### ISSUE THREAD

**Issue by kamalyzl** [kamalyzl/card-validator#1]
#  Archivos principales / Estructura básica

 - [x] README.md con descripción del módulo, instrucciones de instalación, uso y documentación del API.

- [x] index.js: Aquí estará la librería.

- [x] package.json con nombre, versión, descripción, autores, licencia, dependencias, scripts (pretest, test, ...)

- [x] exportar  una función u objeto al entorno global (window) y hacer uso de features de ES6 donde sea apropiado.

- [x] .eslintrc archivo que sirve para la guía de estilos en js 

- [x] .gitignore para ignorar node_modules u otras carpetas que no deban incluirse en control de versiones (git).

- [ X] babelrc.js, archivo que se genera auntomaticamente al instalar babel.js

**Comment by kamalyzl** [comment]
Se utilizó el gestor de tareas Gulp para usar el babel

**Comment by JackelineGCP** [comment]
Nota:
-------
babelrc.js se eliminó este archivo de nuestro proyecto porque usamos el gestor de tareas de Gulp por lo que no es necesario mantenerlo en nuestra carpeta.
