### ISSUE TITLE
Implementación de funcionalidad esencial.

### ISSUE THREAD

**Issue by kamalyzl** [kamalyzl/card-validator#3]
- [x] Función para validar el algoritmo de Luhn

- [X] Función para la validación de datos númerico y de 16 dígitos. 

- [x] Función para la validación del los datos personales (nombre y apellido)

- [x] Función para la validación del código de CVV

- [x] Función para la validación de la  fecha de espiración

- [X] Creación de la data.js para realizar los test en el Demo.

**Comment by kamalyzl** [comment]
Al inicio de las funciones se utlizó regex para condicionar los campos, pero luego al igual los valores de la data, se procedió al retiro,

**Comment by JackelineGCP** [comment]
La estructura de nuestra data.ja será de la siguiente forma:
let persona = [
  {
    number: '4373471036301103',
    name: 'Joalbert',
    cvv: 123,
    fechExp: '2018-01'
  }
];

**Comment by kamalyzl** [comment]
Se realiza cambio de mes y año para facilitar interaccion con usuario

{
    number: '4851519931403589',
    name: 'Juan',
    cvv: '456',
    yy: '22',
    mm: '06'


  },
